#!/usr/bin/env bash
# Install and configure HAProxy load balancer

apt-get update -y
apt-get install -y haproxy

cat > /etc/haproxy/haproxy.cfg <<'EOF'
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 204.236.253.112 check
    server web-02 34.226.152.42 check
EOF

service haproxy restart