#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
WEB_01_IP="3.87.64.87"
WEB_02_IP="WEB_02_IP"  # Replace this with your actual second web server IP
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

