#!/usr/bin/env bash
# Installs nginx and configures it to return "Holberton School for the win!"

# Update package list
apt-get update -y

# Install nginx
apt-get install -y nginx

# Ensure nginx is running
service nginx start

# Create the required page
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart nginx to apply changes
service nginx restart
