#!/usr/bin/env bash
# Install Nginx and create a simple HTML page

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart


