#!/usr/bin/env bash
# Configures nginx to redirect /redirect_me

apt-get update -y
apt-get install -y nginx

# Default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Overwrite nginx default config
cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart nginx
service nginx restart