#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page.

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create a simple web page
echo "Holberton School for the win!" > /var/www/html/index.html

# Add redirection in nginx default config
sed -i '/server_name _;/a\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx (without systemctl)
service nginx restart