#!/usr/bin/env bash
# This script configures Nginx to serve a custom 404 page.

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Create main web page
echo "Holberton School for the win!" > /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Update nginx default config to use custom 404
sed -i '/server_name _;/a\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
